### ISSUE TITLE
更多的视图 & 单笔记本下记录

### ISSUE THREAD

**Issue by Tim-Devil** [jzmanu/siyuan-dashboard#4]
做的很漂亮，但是希望支持更多视图！例如Github的那种热力图的感觉！
未来希望能看到自定义布局和视图！（其实最想实现的就是像github自定义主页那种感觉，不过实现起来想想就觉得会很麻烦，就先当个幻想好了）
哦对了，另外还有一个，就是，既然能统计所有文档的字数，那么或许也能做一个“某笔记本下的字数”？这个功能目前思源还没能实现，感觉未来也不太会去做了。

**Comment by leommjj** [comment]
支持“某笔记本下或者文档下的字数”，因为渐进阅读插件导入的书籍会有干扰

**Comment by jzmanu** [comment]
> 做的很漂亮，但是希望支持更多视图！例如Github的那种热力图的感觉！ 未来希望能看到自定义布局和视图！（其实最想实现的就是像github自定义主页那种感觉，不过实现起来想想就觉得会很麻烦，就先当个幻想好了） 哦对了，另外还有一个，就是，既然能统计所有文档的字数，那么或许也能做一个“某笔记本下的字数”？这个功能目前思源还没能实现，感觉未来也不太会去做了。

某笔记本下的字数，笔记本做成可选择的，热力图的靠后一点。

**Comment by jzmanu** [comment]
> 支持“某笔记本下或者文档下的字数”，因为渐进阅读插件导入的书籍会有干扰

后续设置里面增加要排除的笔记本，也可以选择笔记本，同[上个回复](https://github.com/jzmanu/siyuan-dashboard/issues/4#issuecomment-2521865640)。

**Comment by jzmanu** [comment]
增加了笔记本选择。
